name: clean_core
description: `clean_core` (for dart/flutter) pretende ser un framework para estructurar y organizar el código de una aplicación siguiendo **UNA VARIANTE** de Clean Architecture presentada por Robert C. Martin (Uncle Bob), explicada en su libro Clean Architecture. Esta implementación de la arquitectura que se presenta **NO** sigue al pie de la letra sus estándares, es sino una abstracción adaptada a las comodidades propias de sus desarrolladores.
version: 1.0.1-RELEASE.20211011
homepage: https://github.com/JesusHdezWaterloo/clean-core-flutter.git

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.root101.clean.core.flutter.clean_core
        pluginClass: CleanCorePlugin
      ios:
        pluginClass: CleanCorePlugin
      web:
        pluginClass: CleanCoreWeb
        fileName: clean_core_web.dart