name: clean_core
description: "`clean_core` es framework para estructurar y organizar el código de una aplicación siguiendo UNA VARIANTE de Clean Architecture de Robert C. Martin (Uncle Bob)"
version: 1.3.3-RELEASE.20220407
homepage: https://github.com/JesusHdezWaterloo/clean-core-flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.root101.clean.core.flutter.clean_core
        pluginClass: CleanCorePlugin
      ios:
        pluginClass: CleanCorePlugin
      web:
        pluginClass: CleanCoreWeb
        fileName: clean_core_web.dart